project:
  type: website

website:
  title: "IT Playground"
  navbar:
    background: white
    logo: ./img/tere-logo.webp
    left:
      - href: index.qmd
        text: Home
      - text: "R Basic"
        href: docs/rbasic/index.qmd
      - text: "Blog"
        href: docs/blog/index.qmd
      - talks.qmd
      - about.qmd
    right: 
      - icon: github
        href: "#"
        aria-label: IT Playground
  sidebar:
    - title: "R Basic"
      style: "floating"
      collapse-level: 2
      align: left
      contents: 
        - docs/rbasic/index.qmd
        - docs/rbasic/lec001.qmd
    - title: "talks"
      contents:
        - talks.qmd
    - title: "About"
      contents:
        - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

